[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_toolkit"
version = "0.1.0"
description = "Reusable Machine Learning Toolkit"
authors = [
    {name = "Andrew Wamala Kyanjo"}
]
dependencies = [
    "pandas",
    "scikit-learn"
]

[tool.setuptools.packages.find]
where = ["src"]